[package]
name = "szyszka"
version = "1.0.0"
authors = ["Rafa≈Ç Mikrut <mikrutrafal@protonmail.com>"]
edition = "2018"
description = "Simple, powerful and easy to use file renamer"
license = "MIT"
homepage = "https://github.com/qarmin/szyszka"
repository = "https://github.com/qarmin/szyszka"

[dependencies]
gdk = "0.13.2"
gio = "0.9.1"
glib = "0.10.1"

humansize = "1"
chrono = "0.4"

# For opening files
open = "1.4.0"

[dependencies.gtk]
version = "0.9.2"
default-features = false # just in case
features = ["v3_22"]

