[package]
name = "szyszka"
version = "2.0.0"
authors = ["Rafa≈Ç Mikrut <mikrutrafal@protonmail.com>"]
edition = "2021"
description = "Fast, powerful and easy to use file renamer"
license = "MIT"
homepage = "https://github.com/qarmin/szyszka"
repository = "https://github.com/qarmin/szyszka"

[dependencies]
gdk4 = "0.5.2"
gio = "0.16.3"
glib = "0.16.3"

# For checking path
walkdir = "2.3.2"

humansize = "2.1.2"
chrono = "0.4.23"

# For opening files
open = "3.2.0"

# For slugs
slugmin = "1.0.2"

# Language
i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.4"
rust-embed = "6.4.2"
once_cell = "1.16.0"

[dependencies.gtk4]
version = "0.5.2"
default-features = false # just in case
features = ["v4_6"]

